// export const underscoreFields = [
//     "_conversion_contract_date",
//     "_conversion_completion_date",
//     "_IOPP_manufacturer_14_6",
//     "_IOPP_type_model_14_6",
//     "_IOPP_manufacturer_14_7",
//     "_IOPP_type_model_14_7",
//     "_IOPP_meter_manufacturer",
//     "_IOPP_meter_type_model",
//     "_max_throughput",
//     "_special_voyage_area",
//     "_acceptable_means",
//     "_manual_approve_by_5_3",
//     "_manual_approve_on_5_3",
//     "_manual_approve_by_5_4",
//     "_manual_approve_on_5_4",
//     "_trade_engagement",
//     "_drg_no_5_7",
//     "_approve_by_5_7",
//     "_approve_on_5_7",
//     "_reg_28_6",
//     "_reg_28_5_1",
//     "_admin_verification",
//     "_reg_28_5_3",
//     "_reg_28_5_4",
//     "_input_5_8_4_1",
//     "_input_5_8_4_2",
//     "_input_5_8_4_3",
//     "_input_5_8_6_1",
//     "_input_5_8_6_2",
//     "_input_5_8_6_3",
//     "_input_5_8_6_4",
//     "_IOPP_manufacturer_6_1_a",
//     "_IOPP_type_model_6_1_b",
//     "_category_6_1",
//     "_approve_by_6_1_6",
//     "_approve_on_6_1_6",
//     "_slop_tank_no",
//     "_slop_tank_capacity",
//     "_slop_tank_%",
//     "_input_6_5_1_1",
//     "_input_6_5_1_2",
//     "_input_6_5_1_3",
//     "_approve_by_8_1",
//     "_approve_on_8_1",
//     "_approve_by_8_2",
//     "_approve_on_8_2",
//     "_exemption_para_9_1",
//     "_equivalent_para_10_1"
//   ];
  
export const underscoreFields = [
  "_SAFCON_convention",
  "_SAFCON_inspection_date1",
  "_SAFCON_inspection_date2"
]