version: "3.8"

services:
  # Next.js frontend
  class-admin:
    container_name: class-admin
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "13000:13000"
    env_file:
      - .env
    restart: always
    networks:
      - class-software-dev-network
networks:
  class-software-dev-network:
    external: true
