version: "3.8"

services:
  # Certbot for SSL certificates
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./ssl:/etc/letsencrypt
      - ./ssl-challenge:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot  --non-interactive --agree-tos -d gambiaclass.org -d www.gambiaclass.org -d dev.gambiaclass.org

  # Next.js frontend
  class-admin-dev:
    container_name: class-admin-dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "13000:13000"
    env_file:
      - .env
    restart: always
    networks:
      - class-software-dev-network
networks:
  class-software-dev-network:
    external: true
