version = 4.2.0
archive_dir = /etc/letsencrypt/archive/gambiaclass.org
cert = /etc/letsencrypt/live/gambiaclass.org/cert.pem
privkey = /etc/letsencrypt/live/gambiaclass.org/privkey.pem
chain = /etc/letsencrypt/live/gambiaclass.org/chain.pem
fullchain = /etc/letsencrypt/live/gambiaclass.org/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = 701ec1779032ea42fc612a9548bebb70
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
gambiaclass.org = /var/www/certbot
www.gambiaclass.org = /var/www/certbot
