export const POSITION_OPTIONS = [
  { code: "P", name: "Port" },
  { code: "C", name: "Centre" },
  { code: "S", name: "Starboard" },
  { code: "F", name: "Forward" },
  { code: "A", name: "Aft" },
  { code: "U", name: "Upper" },
  { code: "L", name: "Lower" },
  { code: "PI", name: "Port Inner" },
  { code: "PO", name: "Port Outer" },
  { code: "PF", name: "Port Ford" },
  { code: "PA", name: "Port Aft" },
  { code: "SI", name: "Starboard Inner" },
  { code: "SO", name: "Starboard Outer" },
  { code: "SF", name: "Starboard Ford" },
  { code: "SA", name: "Starboard Aft" },
  { code: "SU", name: "Starboard Upper" },
  { code: "SL", name: "Starboard Lower" },
  { code: "PU", name: "Port Upper" },
  { code: "PL", name: "Port Lower" },
];

// Section definitions with sequential IDs
export const MACHINERY_SECTIONS = {
  1: {
    sectionId: "machinery_list",
    sectionName: "Main Engine",
    codeId: "01",
    rows: [
      { id: "01", label: "Cyl, Cvr, Pstn, Rod, Vlvs & gears", hasFromTo: false, isDue: false, isFrom: false, content: "No {cyl} Cyl, Cvr, Pstn, Rod, Vlvs & gears", repeatPerCylinder: true, isDue: true, isNewlyAdded: false },
      { id: "02", label: "Con Rod, Top end & Guides", hasFromTo: false, isDue: false, isFrom: false, content: "No {cyl}, Con Rod, Top end & Guides", repeatPerCylinder: true, isDue: true, isNewlyAdded: false },
      { id: "03", label: "Crankpin, Bearing & webs", hasFromTo: false, isDue: false, isFrom: false, content: "No {cyl} Crankpin, Bearing & webs", repeatPerCylinder: true, isDue: true, isNewlyAdded: false },
      { id: "04", label: "Main journal and bearing", hasFromTo: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "05", label: "O.F. injection pump, h.p .o.f. pipes & shielding", hasFromTo: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "06", label: "O.F. injection pump and complete o.f. system for common rail system", hasFromTo: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "07", label: "Insulation exhaust manifold and piping", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "08", label: "Hydraulic pump for exhaust valves", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "09", label: "Crankcase doors and relief devices", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "10", label: "Scavenge relief devices", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "11", label: "Crankshaft alignment", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "12", label: "Vibration damper/de-tuner", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "13", label: "Oil mist detector", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "14", label: "Camshaft/s and camshaft/s drive", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "15", label: "Bed plates, frames, tie rods, holding down bolts and chocks", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "16", label: "Starting and reversing gear", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "17", label: "Super charger/Turbocharger", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "18", label: "Electric scavenge blower/ scavenge pump", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "19", label: "Piston cooling water air compressor", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "20", label: "Main engine air cooler", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "21", label: "Engine under piston scavenge air cooler", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "22", label: "Main engine attached bilge pump", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "23", label: "Main engine attached sea water cooling pump", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "24", label: "Main engine attached fresh water cooling pump", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "25", label: "Main engine attached lub. oil circulating pump", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "26", label: "Main engine attached O.F. booster pump", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "27", label: "Main engine attached air compressor", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "28", label: "Main engine attached rocker arm lub. oil pump", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "29", label: "Coupling", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "30", label: "Thrust Bearing", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "31", label: "Engine trial", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
    ],
  },
  2: {
    sectionId: "reduction_gearing",
    sectionName: "Main Reduction Gearing",
    codeId: "02",
    rows: [
      { id: "01", label: "Main Reduction Gearing", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "02", label: "Pinion/s and wheel/s", hasPosition: false, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "03", label: "Shaft/s couplings, clutch(es) and bearing/s", hasPosition: false, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "04", label: "Thrust Bearing", hasPosition: false, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "05", label: "Coupling/clutch for shaft generator", hasPosition: false, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "06", label: "Attached lub. oil pump", hasPosition: false, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "07", label: "Attached lub. oil cooler", hasPosition: false, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "08", label: "Elastic coupling", hasPosition: false, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "09", label: "Foundation bolts and chocks", hasPosition: false, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
    ],
  },
  3: {
    sectionId: "electric_propulsion",
    sectionName: "Electric Propulsion Equipment",
    codeId: "03",
    rows: [
      { id: "01", label: "Electric Propulsion Equipment", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "02", label: "Generator complete", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "03", label: "Control gear, cables, etc. connected with propulsion equipment", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "04", label: "Insulation resistance of propulsion equipment", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "05", label: "Governing", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "06", label: "Propulsion motor", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "07", label: "Cooling arrangement for propulsion unit", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "08", label: "Air Gap", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "09", label: "Holding Down Bolts and Chocks of Propulsion Motor", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "10", label: "Propulsion Motor Trial", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
    ],
  },
  4: {
    sectionId: "steam_turbine_propulsion",
    sectionName: "Main Steam Turbine Propulsion Equipment",
    rows: [
      { id: "01", label: "Main Steam Turbine Propulsion Equipment", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "01", label: "Turbine rotor, casing, diaphragm, nozzle, blade and shroud", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "02", label: "Turbine Shaft Bearings", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "03", label: "Turbine Thrust Bearings", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "04", label: "Governing system", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "05", label: "Holding Down Bolts and Chocks", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "06", label: "Propulsion equipment trial", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
    ],
  },
  5: {
    sectionId: "shafting_arrangement",
    sectionName: "Shafting Arrangement",
    rows: [
      { id: "01", label: "Shafting Arrangement", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "02", label: "Thrust shaft and bearings", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "03", label: "Intermediate shaft and bearing/s", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "04", label: "Coupling/clutch for shafting", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
    ],
  },
  6: {
    sectionId: "auxiliary_machinery",
    sectionName: "Auxiliary Machinery",
    rows: [
      { id: "01", label: "Auxiliary Machinery", hasPosition: false, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "02", label: "Generator aux. engine with attachments and coolers", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "03", label: "Emergency generator engine with attachments and coolers", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "04", label: "Steering gear machinery unit", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "05", label: "Hand operated steering gear", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "06", label: "Windlass machinery unit", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "07", label: "First start arrangement trial", hasPosition: false, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
    ],
  },
  7: {
    sectionId: "compressed_air_system",
    sectionName: "Compressed Air System",
    rows: [
      { id: "01", label: "Compressed Air System", hasPosition: false, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "02", label: "Starting air comp. incl. cooler & safety devices", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "03", label: "Aux. air comp. incl. cooler & safety devices", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "04", label: "Control air comp. incl. cooler & safety devices", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "05", label: "Topping up air comp. incl. cooler & safety devices", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "06", label: "Emergency air comp. incl. cooler, safety devices & engine", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "07", label: "Starting air receiver and safety devices", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "08", label: "Aux. air receiver and safety devices", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "09", label: "Emergency air receiver and safety devices", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "10", label: "Control air receiver and safety devices", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "11", label: "Control air dryer", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
    ],
  },
  8: {
    sectionId: "fuel_system",
    sectionName: "Fuel System",
    rows: [
      { id: "01", label: "Fuel system", hasPosition: false, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "02", label: "Oil fuel transfer pump", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "03", label: "D.O. transfer pump", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "04", label: "O.F. service pump", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "05", label: "O.F. circulating pump", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "06", label: "O.F. booster pump", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "07", label: "D.O. service pump", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "08", label: "D.O. booster pump", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "09", label: "Blend O.F. booster pump", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "10", label: "O.F. pump for main boiler", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "11", label: "O.F. pump for aux. boiler", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "12", label: "Main engine O.F. heater", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "13", label: "Aux. boiler O.F. unit heater", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "14", label: "Purifier O.F. heater", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "15", label: "O.F. blender", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
    ],
  },
  9: {
    sectionId: "lubricating_oil_system",
    sectionName: "Lubricating oil system",
    rows: [
      { id: "01", label: "Lubricating oil system", hasFromTo: false, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "02", label: "Main engine lub. oil pump", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "03", label: "Crosshead lub. oil pump", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "04", label: "Aux. engine lub. oil pump", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "05", label: "Gear box lub. oil pump", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "06", label: "Gear box standby pump", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "07", label: "Stern tube lub. oil pump", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "08", label: "Forward gland circulating pump", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "09", label: "Camshaft lub. oil pump", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "10", label: "Rocker arm lub. oil pump", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "11", label: "Turbocharger lub. oil pump", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "12", label: "Main engine lub. oil cooler", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "13", label: "Aux. engine lub. oil cooler", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "14", label: "Camshaft lub. oil cooler", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "15", label: "Turbocharger lub. oil cooler", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "16", label: "Gear box lub. oil cooler", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "17", label: "Stern tube lub. oil cooler", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "18", label: "Forward gland lub. oil cooler", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "19", label: "Lub Oil Transfer Pump", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
    ],
  },
  10: {
    sectionId: "cooling_system",
    sectionName: "Cooling System",
    rows: [
      { id: "01", label: "Cooling system", hasPosition: false, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "02", label: "Main sea water cooling pump", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "03", label: "Aux. sea water cooling pump", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "04", label: "Harbour sea water cooling pump", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "05", label: "Aux. condenser sea water cooling pump", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "06", label: "Main engine fresh water cooling pump", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "07", label: "Piston cooling fresh water pump", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "08", label: "Fuel valve cooling pump", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "09", label: "Aux. engine fresh water cooling pump", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "10", label: "Main engine fresh water cooler", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "11", label: "Main engine piston fresh water cooler", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "12", label: "Aux. engine fresh water cooler", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "13", label: "Fuel valve fresh water cooler", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "14", label: "Main engine jacket cooling system fresh water heater", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "15", label: "Sea Water/Pipes/Valves/Filters", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "16", label: "Fresh Water/Pipes/Valves/Filters", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
    ],
  },
  11: {
    sectionId: "condensate_system",
    sectionName: "Condensate System",
    rows: [
      { id: "01", label: "Condensate system", hasPosition: false, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "02", label: "Main steam condenser", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "03", label: "Aux. steam condenser", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "04", label: "Atmospheric condenser", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "05", label: "Dump condenser", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "06", label: "O.F. and lub. oil drain cooler", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "07", label: "Cargo oil tank drain cooler", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "08", label: "Condensate cooler", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "09", label: "Main condensate extraction pump", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "10", label: "Aux. condensate extraction pump", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "11", label: "Main condenser air ejector", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "12", label: "Aux. condenser air ejector", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
    ],
  },
  12: {
    sectionId: "feed_water_system",
    sectionName: "Feed Water System",
    rows: [
      { id: "01", label: "Feed water system", hasPosition: false, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "02", label: "Main boiler, turbine driven feed pump", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "03", label: "Main boiler, electric driven feed pump", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "04", label: "Primary boiler feed pump", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "05", label: "Secondary boiler feed pump", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "06", label: "Auxiliary boiler feed pump", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "07", label: "Exhaust gas boiler feed pump", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "08", label: "Exhaust gas boiler economiser circ. pump", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "09", label: "Feed water transfer pump", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "10", label: "Feed water heater, main boiler", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "11", label: "Feed water heater, aux. boiler", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "12", label: "Feed Water/Pipes/Valves/Filters", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
    ],
  },
  13: {
    sectionId: "boiler_steam_system",
    sectionName: "Boiler and Steam System",
    rows: [
      { id: "01", label: "Boiler and steam system", hasPosition: false, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "02", label: "Boiler forced draught fan and prime mover", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "03", label: "Boiler steam air heater", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "04", label: "Superheater", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "05", label: "De-superheater", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
    ],
  },
  14: {
    sectionId: "hydraulic_system",
    sectionName: "Hydraulic System",
    rows: [
      { id: "01", label: "Hydraulic system", hasPosition: false, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "02", label: "Hydraulic pump/servo unit for control pitch propeller", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "03", label: "Circulating pump for pitch propeller system", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "04", label: "Cooler for pitch propeller system", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "05", label: "Pump for coupling", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "06", label: "Pump for remote control system", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "07", label: "Hydraulic pump for anchor handling tug winch", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "08", label: "Cooler for bow thruster system", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "09", label: "Hydraulic pump, relief devices and system for thruster unit", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "10", label: "Hydraulic pump and relief devices for hyd. windlass machy. unit", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "11", label: "Hydraulic module inclusive of pumps, piping etc.", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
    ],
  },
  15: {
    sectionId: "bilge_ballast_system",
    sectionName: "Bilge and Ballast System",
    rows: [
      { id: "01", label: "Bilge and ballast system", hasPosition: false, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "02", label: "Reciprocating bilge pump", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "03", label: "Centrifugal bilge pump", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "04", label: "Central priming pump", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "05", label: "Bilge/ballast/fire pump", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "06", label: "Bilge/G.S. pump", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "07", label: "Fire pump", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "08", label: "Oily water separator bilge pump", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "09", label: "Emergency bilge pump", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "10", label: "Ballast pump", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "11", label: "Emergency fire pump and prime mover", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "12", label: "Bilge Ejector", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "13", label: "Working test of bilge system including Emergency suction", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "14", label: "Ballast Pipes/valves/Filters", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "15", label: "Bilge Pipes/Valves/Filters", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
    ],
  },
  16: {
    sectionId: "unattended_machinery_space",
    sectionName: "Unattended Machinery Space",
    rows: [
      { id: "01", label: "Unattended Machinery Space", hasPosition: false, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "02", label: "Bridge Control", hasPosition: false, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "03", label: "Main Control Station", hasPosition: false, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "04", label: "Bilge Level Alarms", hasPosition: false, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "05", label: "Local Manual Controls", hasPosition: false, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "06", label: "Fire Detection and Prevention", hasPosition: false, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "07", label: "Alarm System Warning and Shut-offs", hasPosition: false, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "08", label: "Electric Supply", hasPosition: false, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
    ],
  },
  17: {
    sectionId: "independent_tanks",
    sectionName: "Independent Tanks",
    rows: [{ id: "01", label: "Tanks which are self-supporting, do not form part of the ship's hull or contribute to the hull strength.", hasPosition: false, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false }],
  },
  18: {
    sectionId: "electrical_system",
    sectionName: "Electrical System",
    rows: [
      { id: "01", label: "Electrical System", hasPosition: false, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "02", label: "Gen. and governor running test", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "03", label: "Switch boards and fittings", hasPosition: false, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "04", label: "Emerg. source of power and associated equip.", hasPosition: false, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "05", label: "Navigating lights, indicators", hasPosition: false, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "06", label: "Cables/expansion boxes/fittings etc.", hasPosition: false, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "07", label: "Circuit breakers", hasPosition: false, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "08", label: "Motor/s, control/s and starter/s", hasPosition: false, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "08", label: "Transformer/s", hasPosition: false, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "09", label: "Megger test", hasPosition: false, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "10", label: "Shaft Generator", hasPosition: false, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
    ],
  },
  19: {
    sectionId: "instrumentation_automation",
    sectionName: "Instrumentation and Automation Equipment",
    rows: [
      { id: "01", label: "Instrumentation and Automation Equipment", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "02", label: "Control system for main engine", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "03", label: "Control system for bow/side thruster", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "04", label: "Control system for control pitch propeller", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "05", label: "Boiler front oil burning unit", hasPosition: false, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
    ],
  },
  20: {
    sectionId: "inert_gas_system",
    sectionName: "Inert Gas System",
    rows: [
      { id: "01", label: "Inert gas system", hasPosition: false, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "02", label: "Blowers", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "03", label: "Gas Scrubber Unit", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "04", label: "Deck Water Seal and Piping", hasPosition: false, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "05", label: "Gas Isolating Valves and Interlock Devices", hasPosition: false, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "06", label: "Gas Piping,Valves and Vent System", hasPosition: false, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "07", label: "Pressure Vacuum Devices", hasPosition: false, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "08", label: "Alarms and Shutdown Systems", hasPosition: false, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "09", label: "Scrubber Cooling Pump", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "10", label: "Scrubber Effluent Discharge pipe and Valves", hasPosition: false, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
    ],
  },
  21: {
    sectionId: "sea_connections",
    sectionName: "Sea Connections",
    rows: [{ id: 1, label: "Sea connections", hasPosition: false, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false }],
  },
  22: {
    sectionId: "thrusters",
    sectionName: "Bow and Aft Thruster",
    rows: [
      { id: "01", label: "Bow thruster/s", hasPosition: false, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "02", label: "Bow thruster propeller", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "03", label: "Bow thruster driving Machinery unit", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "04", label: "Aft thruster propeller", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "05", label: "Aft Thruster Driving Machinery Unit", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
    ],
  },
  23: {
    sectionId: "tailshaft_survey",
    sectionName: "Tailshaft Survey",
    rows: [
      { id: "01", label: "Tailshaft Survey", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "02", label: "Oil Lubricated/Continuous Liner/Non Corrosive", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "03", label: "Crack detection of Screw Shaft Cone", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "04", label: "Approved Oil Gland", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "05", label: "Propeller", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "06", label: "Tailshaft", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "07", label: "Stern Bush & Bearing", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
    ],
  },
  24: {
    sectionId: "waterjet_propulsion",
    sectionName: "Waterjet Propulsion",
    rows: [
      { id: "01", label: "Waterjet Propulsion", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "02", label: "Impeller", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "03", label: "Impeller Shaft", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "04", label: "Shaft Journal", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "05", label: "Impeller Chamber", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
    ],
  },
  25: {
    sectionId: "directional_propulsion",
    sectionName: "Directional Propulsion",
    rows: [
      { id: "01", label: "Directional propulsion", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "02", label: "Blades/Propeller", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "03", label: "Control Linkages/Pitch Indicator", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "04", label: "Hydraulic Unit", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "05", label: "Drive Shaft/Coupling/Cardan Shaft/Clutch Assembly", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "06", label: "Oil cooler and piping", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "07", label: "Steering System/Gear Assembly", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "08", label: "Foundation structure/Tightness of Principal Assemblies", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
    ],
  },
  26: {
    sectionId: "main_aux_boiler",
    sectionName: "Main Boiler / Aux. Oil Fired Boiler / Composite Aux Boiler",
    rows: [
      { id: "01", label: "Main Boiler / Aux. Oil Fired Boiler / Composite Aux Boiler", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "02", label: "Int Examination including Fit of Doors", hasPosition: false, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "03", label: "External Examination including Fire Side & Securing Arrangement", hasPosition: false, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "04", label: "Steam Stop Valves", hasPosition: false, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "05", label: "Safety Valves and Mountings Except Steam Stop Valves", hasPosition: false, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "06", label: "Adjustment of Safety Valve, O.F. Burning & Remote Control", hasPosition: false, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
    ],
  },
  27: {
    sectionId: "exhaust_gas_boiler",
    sectionName: "Exhaust Gas Boiler / Economiser",
    rows: [
      { id: "01", label: "Exhaust Gas Boiler / Economiser", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "02", label: "Internal and External Examination including Mountings", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "03", label: "Adjustment of Safety Valve", hasPosition: false, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
    ],
  },
  28: {
    sectionId: "thermal_oil_heater",
    sectionName: "Thermal Oil Heater",
    rows: [
      { id: "01", label: "Thermal Oil Heater", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "02", label: "Int Examination of Furnace", hasPosition: false, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "03", label: "External Examination including Securing Arrangement", hasPosition: false, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "04", label: "Burner Unit", hasPosition: false, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "05", label: "Safety Devices", hasPosition: false, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "06", label: "Oil Piping", hasPosition: false, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
    ],
  },
  29: {
    sectionId: "steam_pipes",
    sectionName: "Steam Pipes (for pipes over 75 mm NB)",
    rows: [{ id: "01", label: "Steam pipes (for pipes over 75 mm NB)", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false }],
  },
  30: {
    sectionId: "refrigerated_cargo_system",
    sectionName: "Refrigerated Cargo System",
    rows: [
      { id: "01", label: "Refrigerated Cargo system", hasPosition: true, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "02", label: "Cargo tank insulation & vapour seal", hasPosition: false, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "03", label: "Vent Stack Drain Tank", hasPosition: false, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "04", label: "Reciprocating compressor", hasPosition: false, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "05", label: "Gas Tight Bulkhead Glands", hasPosition: false, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "06", label: "Cargo Condenser (Examination)", hasPosition: false, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "07", label: "Cargo Condenser (Pressure test)", hasPosition: false, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "08", label: "Suction Separator", hasPosition: false, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "09", label: "Pressure Relief Valves", hasPosition: false, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "10", label: "Sea Water Circulating Pump", hasPosition: false, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "11", label: "Glycol Circulating pump", hasPosition: false, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "12", label: "Inter Stage Cooler for Cargo Compressor", hasPosition: false, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "13", label: "Cargo Heater for Booster pump", hasPosition: false, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "14", label: "Fresh Water/Glycol Heat Exchanger", hasPosition: false, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "15", label: "Automatic Controls & Alarms", hasPosition: false, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "16", label: "Electrical Insulation", hasPosition: false, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "17", label: "Intermediate cooler", hasPosition: false, isDue: true, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
    ],
  },
};

export const HULL_SECTIONS = {
  31: {
    sectionId: "thickness_measurement",
    sectionName: "Thickness Measurement",
    rows: [{ id: "01", label: "Thickness measurement", hasPosition: false, isDue: false, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false }],
  },
  32: {
    sectionId: "superstructures",
    sectionName: "Superstructures",
    rows: [
      { id: "01", label: "Superstructures", hasPosition: false, isDue: false, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "02", label: "Forecastle", hasPosition: false, isDue: false, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "03", label: "Raised fore deck", hasPosition: false, isDue: false, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "04", label: "Bridge superstructure", hasPosition: false, isDue: false, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "05", label: "Raised quarter deck", hasPosition: false, isDue: false, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "06", label: "Poop", hasPosition: false, isDue: false, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
    ],
  },
  33: {
    sectionId: "weather_superstructure_deck",
    sectionName: "Exposed Weather Deck and Superstructure Deck Plating",
    rows: [
      { id: "01", label: "Exposed weather deck and superstructure deck plating", hasPosition: false, isDue: false, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "02", label: "Upper deck plating", hasPosition: false, isDue: false, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "03", label: "Forecastle deck plating", hasPosition: false, isDue: false, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "04", label: "Raised fore deck plating", hasPosition: false, isDue: false, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "05", label: "Bridge deck plating", hasPosition: false, isDue: false, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "06", label: "Raised quarter deck plating", hasPosition: false, isDue: false, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "07", label: "Poop deck plating", hasPosition: false, isDue: false, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "08", label: "Deckhouse", hasPosition: false, isDue: false, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
    ],
  },
  34: {
    sectionId: "spaces_forecastle_poops",
    sectionName: "Spaces in Forecastle and Poop",
    rows: [
      { id: "01", label: "Forecastle tween deck space/s", hasPosition: false, isDue: false, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "02", label: "Poop tween deck space/s", hasPosition: false, isDue: false, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
    ],
  },
  35: {
    sectionId: "spaces_peak_tanks_stores",
    sectionName: "Spaces Above Fore and Aft Peak Tanks; Stores and Accommodation Spaces",
    rows: [
      { id: "01", label: "Spaces above fore and aft peak tanks; stores and accommodation spaces", hasPosition: false, isDue: false, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "02", label: "Fore peak Deck space/s", hasPosition: true, isDue: false, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "03", label: "Aft peak Deck space/s", hasPosition: true, isDue: false, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "04", label: "Accommodation space/s", hasPosition: true, isDue: false, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "05", label: "Store space/s", hasPosition: true, isDue: false, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
    ],
  },
  36: {
    sectionId: "engine_pump_boiler_spaces",
    sectionName: "Engine room, pump room and boiler spaces",
    rows: [
      { id: "01", label: "Engine room, pump room and boiler spaces", hasPosition: false, isDue: false, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "02", label: "Engine room", hasPosition: true, isDue: false, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "03", label: "Pump room", hasPosition: true, isDue: false, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "04", label: "Boiler room", hasPosition: true, isDue: false, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "05", label: "Chain locker", hasPosition: true, isDue: false, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
    ],
  },
  37: {
    sectionId: "holds_tween_decks",
    sectionName: "Holds and Tween decks (excluding tankers)",
    rows: [
      { id: "01", label: "Holds and Tween decks (excluding tankers)", hasPosition: false, isDue: false, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "02", label: "No.1 Hold", hasPosition: true, isDue: false, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "03", label: "No.2 Hold", hasPosition: true, isDue: false, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "04", label: "No.3 Hold", hasPosition: true, isDue: false, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "05", label: "No.4 Hold", hasPosition: true, isDue: false, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "06", label: "No.5 Hold", hasPosition: true, isDue: false, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "07", label: "No.6 Hold", hasPosition: true, isDue: false, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "08", label: "No.7 Hold", hasPosition: true, isDue: false, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "09", label: "No.8 Hold", hasPosition: true, isDue: false, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "10", label: "Hold/WB Tank", hasPosition: true, isDue: false, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "11", label: "Hold/Cargo oil tank", hasPosition: true, isDue: false, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "12", label: "Cargo oil tank/s", hasPosition: true, isDue: false, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
    ],
  },
  38: {
    sectionId: "tween_decks",
    sectionName: "Tween Deck/s",
    rows: [
      { id: "01", label: "Upper tween deck space", hasPosition: true, isDue: false, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "02", label: "Lower tween deck space", hasPosition: true, isDue: false, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
    ],
  },
  39: {
    sectionId: "cargo_tank_for_tankers_only",
    sectionName: "Cargo tanks for tankers only",
    rows: [
      { id: "01", label: "Cargo tanks for tankers only", hasPosition: false, isDue: false, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      {
        id: "02",
        label: "No.1 Cargo tank",
        hasPosition: true,
        isDue: false,
        isFrom: false,
        repeatPerCylinder: false,
        isTankRow: true,
        isNewlyAdded: false,
      },
      {
        id: "03",
        label: "No.2 Cargo tank",
        hasPosition: true,
        isDue: false,
        isFrom: false,
        repeatPerCylinder: false,
        isTankRow: true,
        isNewlyAdded: false,
      },
      {
        id: "04",
        label: "No.3 Cargo tank",
        hasPosition: true,
        isDue: false,
        isFrom: false,
        repeatPerCylinder: false,
        isTankRow: true,
        isNewlyAdded: false,
      },
      {
        id: "05",
        label: "No.4 Cargo tank",
        hasPosition: true,
        isDue: false,
        isFrom: false,
        repeatPerCylinder: false,
        isTankRow: true,
        isNewlyAdded: false,
      },
      {
        id: "06",
        label: "No.5 Cargo tank",
        hasPosition: true,
        isDue: false,
        isFrom: false,
        repeatPerCylinder: false,
        isTankRow: true,
        isNewlyAdded: false,
      },
      {
        id: "07",
        label: "No.6 Cargo tank",
        hasPosition: true,
        isDue: false,
        isFrom: false,
        repeatPerCylinder: false,
        isTankRow: true,
        isNewlyAdded: false,
      },
      {
        id: "08",
        label: "No.7 Cargo tank",
        hasPosition: true,
        isDue: false,
        isFrom: false,
        repeatPerCylinder: false,
        isTankRow: true,
        isNewlyAdded: false,
      },
      {
        id: "09",
        label: "No.8 Cargo tank",
        hasPosition: true,
        isDue: false,
        isFrom: false,
        repeatPerCylinder: false,
        isTankRow: true,
        isNewlyAdded: false,
      },
      {
        id: "10",
        label: "No.9 Cargo tank",
        hasPosition: true,
        isDue: false,
        isFrom: false,
        repeatPerCylinder: false,
        isTankRow: true,
        isNewlyAdded: false,
      },
    ],
  },
  40: {
    sectionId: "slop_tanks",
    sectionName: "Slop tank/s",
    rows: [
      {
        id: "01",
        label: "Slop tank/s",
        hasPosition: false,
        isDue: false,
        isFrom: true,
        repeatPerCylinder: false,
        isTankRow: true,
        isNewlyAdded: false,
      },
      {
        id: "02",
        label: "No.1 Slop tank",
        hasPosition: true,
        isDue: false,
        isFrom: true,
        repeatPerCylinder: false,
        isTankRow: true,
        isNewlyAdded: false,
      },
      {
        id: "03",
        label: "No.2 Slop tank",
        hasPosition: true,
        isDue: false,
        isFrom: true,
        repeatPerCylinder: false,
        isTankRow: true,
        isNewlyAdded: false,
      },
    ],
  },
  41: {
    sectionId: "dry_tanks_void_spaces",
    sectionName: "Dry tanks/void spaces",
    rows: [
      {
        id: "01",
        label: "Dry tanks/void spaces",
        hasPosition: false,
        isDue: false,
        isFrom: true,
        repeatPerCylinder: false,
        isTankRow: true,
        isNewlyAdded: false,
      },
    ],
  },
  42: {
    sectionId: "peak_tanks",
    sectionName: "Peak tanks",
    rows: [
      {
        id: "01",
        label: "Peak tanks",
        hasPosition: false,
        isDue: false,
        isFrom: false,
        repeatPerCylinder: false,
        isTankRow: true,
        isNewlyAdded: false,
      },
      {
        id: "02",
        label: "Forepeak Tank",
        hasPosition: true,
        isDue: false,
        isFrom: true,
        repeatPerCylinder: false,
        isTankRow: true,
        isNewlyAdded: false,
      },
      {
        id: "03",
        label: "Aft Peak Tank",
        hasPosition: true,
        isDue: false,
        isFrom: true,
        repeatPerCylinder: false,
        isTankRow: true,
        isNewlyAdded: false,
      },
    ],
  },
  43: {
    sectionId: "W.B & Storage tank/s",
    sectionName: "W.B & Storage tank/s",
    rows: [
      {
        id: "01",
        label: "W.B & Storage tank/s in the following order: side tanks; topside tanks; deep tanks; double bottom tanks; other engine room tanks (excluding independent tanks); other tanks not intended for carriage of cargo",
        hasPosition: false,
        isDue: false,
        isFrom: true,
        repeatPerCylinder: false,
        isTankRow: true,
        isNewlyAdded: false,
      },
    ],
  },
  44: {
    sectionId: "Duct keels/Cofferdams/Stool spaces",
    sectionName: "Duct keels/Cofferdams/Stool spaces (for Bulk carriers)",
    rows: [
      {
        id: "01",
        label: "Duct keels/Cofferdams/Stool spaces (for Bulk carriers)",
        hasPosition: true,
        isDue: false,
        isFrom: true,
        repeatPerCylinder: false,
        isNewlyAdded: false,
      },
      {
        id: "02",
        label: "Aft Transverse Bulkhead Upper Stool Space",
        hasPosition: true,
        isDue: false,
        isFrom: true,
        repeatPerCylinder: false,
        isNewlyAdded: false,
      },
      {
        id: "03",
        label: "Aft Transverse Bulkhead Lower Stool Space",
        hasPosition: true,
        isDue: false,
        isFrom: true,
        repeatPerCylinder: false,
        isNewlyAdded: false,
      },
    ],
  },
  45: {
    sectionId: "tunnels",
    sectionName: "Tunnel/s",
    rows: [
      {
        id: "01",
        label: "Tunnel/s",
        hasPosition: false,
        isDue: false,
        isFrom: false,
        repeatPerCylinder: false,
        isNewlyAdded: false,
      },
      {
        id: "02",
        label: "Shaft tunnel",
        hasPosition: true,
        isDue: false,
        isFrom: false,
        repeatPerCylinder: false,
        isNewlyAdded: false,
      },
      {
        id: "03",
        label: "Tunnel well",
        hasPosition: true,
        isDue: false,
        isFrom: false,
        repeatPerCylinder: false,
        isNewlyAdded: false,
      },
      {
        id: "04",
        label: "Under deck tunnel",
        hasPosition: true,
        isDue: false,
        isFrom: false,
        repeatPerCylinder: false,
        isNewlyAdded: false,
      },
    ],
  },
  46: {
    sectionId: "under_engine_boiler",
    sectionName: "Under engine/s/boiler/s",
    rows: [
      {
        id: "01",
        label: "Under engine/s/boiler/s",
        hasPosition: false,
        isDue: false,
        isFrom: false,
        repeatPerCylinder: false,
        isNewlyAdded: false,
      },
      {
        id: "02",
        label: "Under engines",
        hasPosition: false,
        isDue: false,
        isFrom: false,
        repeatPerCylinder: false,
        isNewlyAdded: false,
      },
      {
        id: "03",
        label: "Under boilers",
        hasPosition: false,
        isDue: false,
        isFrom: false,
        repeatPerCylinder: false,
      },
    ],
  },
  47: {
    sectionId: "misc_compartments",
    sectionName: "Misc. compartments",
    rows: [
      {
        id: "01",
        label: "Misc. compartments",
        hasPosition: false,
        isDue: false,
        isFrom: false,
        repeatPerCylinder: false,
        isNewlyAdded: false,
      },
      {
        id: "02",
        label: "Echo sounding compartment",
        hasPosition: true,
        isDue: false,
        isFrom: false,
        repeatPerCylinder: false,
        isNewlyAdded: false,
      },
      {
        id: "03",
        label: "Steering gear compartment",
        hasPosition: true,
        isDue: false,
        isFrom: false,
        repeatPerCylinder: false,
        isNewlyAdded: false,
      },
      {
        id: "04",
        label: "Bow thrust compartment",
        hasPosition: true,
        isDue: false,
        isFrom: false,
        repeatPerCylinder: false,
        isNewlyAdded: false,
      },
      {
        id: "05",
        label: "Emergency Fire Pump Compartment",
        hasPosition: true,
        isDue: false,
        isFrom: false,
        repeatPerCylinder: false,
        isNewlyAdded: false,
      },
      {
        id: "06",
        label: "Paint Locker",
        hasPosition: true,
        isDue: false,
        isFrom: false,
        repeatPerCylinder: false,
        isNewlyAdded: false,
      },
    ],
  },
  48: {
    sectionId: "misc_items",
    sectionName: "Misc. items",
    rows: [
      { id: "01", label: "Misc. items", hasPosition: true, isDue: false, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "02", label: "Windlass", hasPosition: false, isDue: false, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "03", label: "Anchor/s", hasPosition: false, isDue: false, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "04", label: "Cable/s", hasPosition: false, isDue: false, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "05", label: "Steering gear", hasPosition: false, isDue: false, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "06", label: "Aux. steering gear", hasPosition: false, isDue: false, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "07", label: "Hand pump/s", hasPosition: false, isDue: false, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "08", label: "Sounding pipes", hasPosition: false, isDue: false, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "09", label: "Air pipe/s and closing appliances", hasPosition: false, isDue: false, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "10", label: "Mast/s", hasPosition: false, isDue: false, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "11", label: "Rigging", hasPosition: false, isDue: false, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "12", label: "Fire equipment", hasPosition: false, isDue: false, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "13", label: "Means of escape", hasPosition: false, isDue: false, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "14", label: "Communication – Steering gear related", hasPosition: false, isDue: false, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "15", label: "Helm indicator", hasPosition: false, isDue: false, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "16", label: "Watertight door/s", hasPosition: false, isDue: false, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "17", label: "Hatchways and closing appliances", hasPosition: false, isDue: false, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "18", label: "Ventilators and closing appliances", hasPosition: false, isDue: false, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "19", label: "Casings and their closing appliances", hasPosition: false, isDue: false, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "20", label: "Skylights and closing appliances", hasPosition: false, isDue: false, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "21", label: "Deckhouses, companionways and closing appliances", hasPosition: false, isDue: false, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "22", label: "Superstructures and closing appliances", hasPosition: false, isDue: false, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "23", label: "Side, bow, stern doors and closing appliances", hasPosition: false, isDue: false, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "24", label: "Windows, side scuttles, deadlights and closing appliances", hasPosition: false, isDue: false, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "25", label: "Refuse chutes etc. and closing appliances", hasPosition: false, isDue: false, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "26", label: "Scuppers, sanitary discharges and valves", hasPosition: false, isDue: false, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "27", label: "Guard rails and bulwarks", hasPosition: false, isDue: false, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "28", label: "Freeing ports", hasPosition: false, isDue: false, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "29", label: "Gangways, walkways and lifelines", hasPosition: false, isDue: false, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "30", label: "Fittings for timber deck cargo", hasPosition: false, isDue: false, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "31", label: "Towing Hook/Winch and Associated under deck structures", hasPosition: true, isDue: false, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "32", label: "Emergency Towing Arrangement", hasPosition: true, isDue: false, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
      { id: "33", label: "Safe Access to Tanker Bow", hasPosition: true, isDue: false, isFrom: false, repeatPerCylinder: false, isNewlyAdded: false },
    ],
  },
};
