name: Deploy to Hostinger VPS - 2

on:
  push:
    branches:
      - main
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Deploy to VPS
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          CURRENT_BRANCH: ${{ github.head_ref || github.ref_name }}
        shell: bash
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          ssh -o StrictHostKeyChecking=no root@89.116.34.232 <<EOF
            source ~/.bashrc
            export CURRENT_BRANCH="$CURRENT_BRANCH"

            cd
            cd front/class-software-admin
            
            if [ ${CURRENT_BRANCH} == "main" ]; then
              ls -la
              git checkout main
              git pull origin main
              cp .env.main .env
              cat .env
              npm install --legacy-peer-deps
              npm run build
              pm2 delete class-software-admin-main
              pm2 flush
              PORT=3013 pm2 start npm --name "class-software-admin-main" -- start
              pm2 save
            elif [ ${CURRENT_BRANCH} == "development" ]; then
              ls -la
              git checkout development
              git pull origin development
              cat .env
              npm install --legacy-peer-deps
              npm run build
              pm2 delete class-software-admin-development
              pm2 flush
              PORT=3014 pm2 start npm --name "class-software-admin-development" -- start
              pm2 save           
            else
              exit 1
            fi
          EOF
